/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface DrivetrainTelemetry {}
  interface GyroInfoSmall {}
  interface KeyValueText {
    'color': string;
    'reversed': boolean;
    'units': string;
    'value': any;
  }
  interface ShooterTelemetry {}
  interface SparkMaxInfoSmall {
    'alignRight': boolean;
  }
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLDrivetrainTelemetryElement extends Components.DrivetrainTelemetry, HTMLStencilElement {}
  var HTMLDrivetrainTelemetryElement: {
    prototype: HTMLDrivetrainTelemetryElement;
    new (): HTMLDrivetrainTelemetryElement;
  };

  interface HTMLGyroInfoSmallElement extends Components.GyroInfoSmall, HTMLStencilElement {}
  var HTMLGyroInfoSmallElement: {
    prototype: HTMLGyroInfoSmallElement;
    new (): HTMLGyroInfoSmallElement;
  };

  interface HTMLKeyValueTextElement extends Components.KeyValueText, HTMLStencilElement {}
  var HTMLKeyValueTextElement: {
    prototype: HTMLKeyValueTextElement;
    new (): HTMLKeyValueTextElement;
  };

  interface HTMLShooterTelemetryElement extends Components.ShooterTelemetry, HTMLStencilElement {}
  var HTMLShooterTelemetryElement: {
    prototype: HTMLShooterTelemetryElement;
    new (): HTMLShooterTelemetryElement;
  };

  interface HTMLSparkMaxInfoSmallElement extends Components.SparkMaxInfoSmall, HTMLStencilElement {}
  var HTMLSparkMaxInfoSmallElement: {
    prototype: HTMLSparkMaxInfoSmallElement;
    new (): HTMLSparkMaxInfoSmallElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'drivetrain-telemetry': HTMLDrivetrainTelemetryElement;
    'gyro-info-small': HTMLGyroInfoSmallElement;
    'key-value-text': HTMLKeyValueTextElement;
    'shooter-telemetry': HTMLShooterTelemetryElement;
    'spark-max-info-small': HTMLSparkMaxInfoSmallElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface DrivetrainTelemetry {}
  interface GyroInfoSmall {}
  interface KeyValueText {
    'color'?: string;
    'reversed'?: boolean;
    'units'?: string;
    'value'?: any;
  }
  interface ShooterTelemetry {}
  interface SparkMaxInfoSmall {
    'alignRight'?: boolean;
  }

  interface IntrinsicElements {
    'app-root': AppRoot;
    'drivetrain-telemetry': DrivetrainTelemetry;
    'gyro-info-small': GyroInfoSmall;
    'key-value-text': KeyValueText;
    'shooter-telemetry': ShooterTelemetry;
    'spark-max-info-small': SparkMaxInfoSmall;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'drivetrain-telemetry': LocalJSX.DrivetrainTelemetry & JSXBase.HTMLAttributes<HTMLDrivetrainTelemetryElement>;
      'gyro-info-small': LocalJSX.GyroInfoSmall & JSXBase.HTMLAttributes<HTMLGyroInfoSmallElement>;
      'key-value-text': LocalJSX.KeyValueText & JSXBase.HTMLAttributes<HTMLKeyValueTextElement>;
      'shooter-telemetry': LocalJSX.ShooterTelemetry & JSXBase.HTMLAttributes<HTMLShooterTelemetryElement>;
      'spark-max-info-small': LocalJSX.SparkMaxInfoSmall & JSXBase.HTMLAttributes<HTMLSparkMaxInfoSmallElement>;
    }
  }
}


