/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface SparkMaxInfoSmall {}
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLSparkMaxInfoSmallElement extends Components.SparkMaxInfoSmall, HTMLStencilElement {}
  var HTMLSparkMaxInfoSmallElement: {
    prototype: HTMLSparkMaxInfoSmallElement;
    new (): HTMLSparkMaxInfoSmallElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'spark-max-info-small': HTMLSparkMaxInfoSmallElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface SparkMaxInfoSmall {}

  interface IntrinsicElements {
    'app-root': AppRoot;
    'spark-max-info-small': SparkMaxInfoSmall;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'spark-max-info-small': LocalJSX.SparkMaxInfoSmall & JSXBase.HTMLAttributes<HTMLSparkMaxInfoSmallElement>;
    }
  }
}


